import Mathlib.CategoryTheory.Elements
import Mathlib.CategoryTheory.PathCategory.Basic
import Formalize.Miner

/-!
# Static copresheaf bridge

This module gives the miner/proposer pipeline a small, checkable categorical
model without making Lean execute the live pipeline.

`ArtifactType` is the schema of artifact classes.  `ArtifactOp` is the quiver of
generating transitions between those classes.  `Schema` is the free category on
that quiver, so Mathlib supplies identities, composition, and associativity.

An artifact state is then just a copresheaf on the schema, implemented as a
Mathlib functor `Schema ⥤ Type`.  `initialState` is a static snapshot-style
example: it maps a mined declaration to a well-formed statement candidate, then
to a pending proof outcome.  The live Python miner/proposer/oracle continues to
write JSON and call external tools outside this pure Lean model.
-/

namespace Formalize.PaperBridge

open CategoryTheory

/-- The artifact classes tracked by the current demo pipeline. -/
inductive ArtifactType where
  | minedDecl
  | wellFormedStatement
  | proofOutcome
  deriving Repr, DecidableEq, Inhabited

/-- Generating pipeline transitions between artifact classes. -/
inductive ArtifactOp : ArtifactType → ArtifactType → Type where
  | checkWellFormed : ArtifactOp .minedDecl .wellFormedStatement
  | runOracle : ArtifactOp .wellFormedStatement .proofOutcome

instance : Quiver ArtifactType where
  Hom := ArtifactOp

/-- The free schema category generated by the artifact quiver. -/
abbrev Schema := Paths ArtifactType

/-- A statement candidate that has passed into the statement layer of the schema. -/
structure WellFormedStatement where
  source : Lean.Name
  statement : String
  deriving Repr

/-- The proof status tracked by the static bridge. -/
inductive ProofOutcome where
  | pending
  | checked
  | missed
  | unusable
  deriving Repr, DecidableEq, Inhabited

/-- A copresheaf-valued artifact state on the schema category. -/
abbrev ArtifactState := Schema ⥤ Type

/-- The prefunctor data on generators.  `Paths.lift` turns this into a real functor. -/
def initialStateProto : ArtifactType ⥤q Type where
  obj
    | .minedDecl => Formalize.MinedDecl
    | .wellFormedStatement => WellFormedStatement
    | .proofOutcome => ProofOutcome
  map
    | .checkWellFormed => fun d => { source := d.name, statement := d.statement }
    | .runOracle => fun _ => ProofOutcome.pending

/-- A static copresheaf describing the artifact state after choosing the generator maps. -/
def initialState : ArtifactState :=
  Paths.lift initialStateProto

/-- The category of elements is the provenance category of concrete artifacts. -/
abbrev Provenance (I : ArtifactState) := I.Elements

/-- A deterministic sample declaration used to typecheck the bridge. -/
def sampleMinedDecl : Formalize.MinedDecl where
  name := `CategoryTheory.sample
  kind := Formalize.DeclKind.theorem
  statement := "True"

/-- The sample object at the mined-declaration layer of the provenance category. -/
def sampleMinedArtifact : Provenance initialState :=
  initialState.elementsMk ArtifactType.minedDecl sampleMinedDecl

/-- The sample object after applying the `checkWellFormed` generator. -/
def sampleCheckedArtifact : Provenance initialState :=
  initialState.elementsMk ArtifactType.wellFormedStatement
    (initialState.map (Quiver.Hom.toPath ArtifactOp.checkWellFormed) sampleMinedDecl)

/-- The sample object after applying the two-step path through the schema. -/
def sampleProofArtifact : Provenance initialState :=
  initialState.elementsMk ArtifactType.proofOutcome
    (initialState.map
      (Quiver.Path.cons (Quiver.Hom.toPath ArtifactOp.checkWellFormed) ArtifactOp.runOracle)
      sampleMinedDecl)

example :
    initialState.map (Quiver.Hom.toPath ArtifactOp.checkWellFormed) sampleMinedDecl =
      { source := sampleMinedDecl.name, statement := sampleMinedDecl.statement } :=
  rfl

example :
    initialState.map
      (Quiver.Path.cons (Quiver.Hom.toPath ArtifactOp.checkWellFormed) ArtifactOp.runOracle)
      sampleMinedDecl = ProofOutcome.pending :=
  rfl

end Formalize.PaperBridge
